using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MyAZHRM.Helpers
{
    public class CurrencyInfo
    {
        public List<string> getCurrencies()
        {
            List<string> currencies = new List<string>();

            currencies.Add("USD - United States Dollar");
            currencies.Add("INR - Indian Rupee");
            currencies.Add("EUR - Euro");
            currencies.Add("GBP - British Pound Sterling");
            currencies.Add("CAD - Canadian Dollar");
            currencies.Add("JPY - Japanese Yen");
            currencies.Add("AFN - Afghan Afghani");
            currencies.Add("ALL - Albanian Lek");
            currencies.Add("AMD - Armenian Dram");
            currencies.Add("AOA - Angolan Kwanza");
            currencies.Add("ARS - Argentine Peso");
            currencies.Add("AUD - Australian Dollar");
            currencies.Add("AWG - Aruban Florin");
            currencies.Add("AZN - Azerbaijani Manat");
            currencies.Add("DZD - Algerian Dinar");
            currencies.Add("BAM - Bosnia-Herzegovina Convertible Mark");
            currencies.Add("BBD - Barbadian Dollar");
            currencies.Add("BDT - Bangladeshi Taka");
            currencies.Add("BGN - Bulgarian Lev");
            currencies.Add("BHD - Bahraini Dinar");
            currencies.Add("BIF - Burundian Franc");
            currencies.Add("BMD - Bermudan Dollar");
            currencies.Add("BND - Brunei Dollar");
            currencies.Add("BOB - Bolivian Boliviano");
            currencies.Add("BRL - Brazilian Real");
            currencies.Add("BSD - Bahamian Dollar");
            currencies.Add("BTN - Bhutanese Ngultrum");
            currencies.Add("BWP - Botswanan Pula");
            currencies.Add("BYR - Belarusian Ruble");
            currencies.Add("BZD - Belize Dollar");
            currencies.Add("GBP - British Pound Sterling");
            currencies.Add("CAD - Canadian Dollar");
            currencies.Add("CDF - Congolese Franc");
            currencies.Add("CLF - Chilean Unit of Account (UF)");
            currencies.Add("CLP - Chilean Peso");
            currencies.Add("CNY - Chinese Yuan");
            currencies.Add("COP - Colombian Peso");
            currencies.Add("CRC - Costa Rican Colón");
            currencies.Add("CUC - Cuban Convertible Peso");
            currencies.Add("CUP - Cuban Peso");
            currencies.Add("CVE - Cape Verdean Escudo");
            currencies.Add("CZK - Czech Republic Koruna");
            currencies.Add("HRK - Croatian Kuna");
            currencies.Add("KHR - Cambodian Riel");
            currencies.Add("KMF - Comorian Franc");
            currencies.Add("KYD - Cayman Islands Dollar");
            currencies.Add("XAF - CFA Franc BEAC");
            currencies.Add("XOF - CFA Franc BCEAO");
            currencies.Add("XPF - CFP Franc");
            currencies.Add("DJF - Djiboutian Franc");
            currencies.Add("DKK - Danish Krone");
            currencies.Add("DOP - Dominican Peso");
            currencies.Add("EGP - Egyptian Pound");
            currencies.Add("ERN - Eritrean Nakfa");
            currencies.Add("ETB - Ethiopian Birr");
            currencies.Add("EUR - Euro");
            currencies.Add("XCD - East Caribbean Dollar");
            currencies.Add("FJD - Fijian Dollar");
            currencies.Add("FKP - Falkland Islands Pound");
            currencies.Add("GEL - Georgian Lari");
            currencies.Add("GGP - Guernsey Pound");
            currencies.Add("GHS - Ghanaian Cedi");
            currencies.Add("GIP - Gibraltar Pound");
            currencies.Add("GMD - Gambian Dalasi");
            currencies.Add("GNF - Guinean Franc");
            currencies.Add("GTQ - Guatemalan Quetzal");
            currencies.Add("GYD - Guyanaese Dollar");
            currencies.Add("XAU - Gold (troy ounce)");
            currencies.Add("HKD - Hong Kong Dollar");
            currencies.Add("HNL - Honduran Lempira");
            currencies.Add("HTG - Haitian Gourde");
            currencies.Add("HUF - Hungarian Forint");
            currencies.Add("IDR - Indonesian Rupiah");
            currencies.Add("ILS - Israeli New Sheqel");
            currencies.Add("INR - Indian Rupee");
            currencies.Add("IQD - Iraqi Dinar");
            currencies.Add("IRR - Iranian Rial");
            currencies.Add("ISK - Icelandic Króna");
            currencies.Add("JEP - Jersey Pound");
            currencies.Add("JMD - Jamaican Dollar");
            currencies.Add("JOD - Jordanian Dinar");
            currencies.Add("JPY - Japanese Yen");
            currencies.Add("KES - Kenyan Shilling");
            currencies.Add("KGS - Kyrgystani Som");
            currencies.Add("KWD - Kuwaiti Dinar");
            currencies.Add("KZT - Kazakhstani Tenge");
            currencies.Add("LAK - Laotian Kip");
            currencies.Add("LBP - Lebanese Pound");
            currencies.Add("LRD - Liberian Dollar");
            currencies.Add("LSL - Lesotho Loti");
            currencies.Add("LTL - Lithuanian Litas");
            currencies.Add("LVL - Latvian Lats");
            currencies.Add("LYD - Libyan Dinar");
            currencies.Add("IMP - Manx pound");
            currencies.Add("MAD - Moroccan Dirham");
            currencies.Add("MDL - Moldovan Leu");
            currencies.Add("MGA - Malagasy Ariary");
            currencies.Add("MKD - Macedonian Denar");
            currencies.Add("MMK - Myanma Kyat");
            currencies.Add("MNT - Mongolian Tugrik");
            currencies.Add("MOP - Macanese Pataca");
            currencies.Add("MRO - Mauritanian Ouguiya");
            currencies.Add("MUR - Mauritian Rupee");
            currencies.Add("MVR - Maldivian Rufiyaa");
            currencies.Add("MWK - Malawian Kwacha");
            currencies.Add("MXN - Mexican Peso");
            currencies.Add("MYR - Malaysian Ringgit");
            currencies.Add("MZN - Mozambican Metical");
            currencies.Add("ANG - Netherlands Antillean Guilder");
            currencies.Add("BYN - New Belarusian Ruble");
            currencies.Add("KPW - North Korean Won");
            currencies.Add("NAD - Namibian Dollar");
            currencies.Add("NGN - Nigerian Naira");
            currencies.Add("NIO - Nicaraguan Córdoba");
            currencies.Add("NOK - Norwegian Krone");
            currencies.Add("NPR - Nepalese Rupee");
            currencies.Add("NZD - New Zealand Dollar");
            currencies.Add("TWD - New Taiwan Dollar");
            currencies.Add("OMR - Omani Rial");
            currencies.Add("PAB - Panamanian Balboa");
            currencies.Add("PEN - Peruvian Nuevo Sol");
            currencies.Add("PGK - Papua New Guinean Kina");
            currencies.Add("PHP - Philippine Peso");
            currencies.Add("PKR - Pakistani Rupee");
            currencies.Add("PLN - Polish Zloty");
            currencies.Add("PYG - Paraguayan Guarani");
            currencies.Add("QAR - Qatari Rial");
            currencies.Add("RON - Romanian Leu");
            currencies.Add("RUB - Russian Ruble");
            currencies.Add("RWF - Rwandan Franc");
            currencies.Add("CHF - Swiss Franc");
            currencies.Add("KRW - South Korean Won");
            currencies.Add("LKR - Sri Lankan Rupee");
            currencies.Add("RSD - Serbian Dinar");
            currencies.Add("SAR - Saudi Riyal");
            currencies.Add("SBD - Solomon Islands Dollar");
            currencies.Add("SCR - Seychellois Rupee");
            currencies.Add("SDG - Sudanese Pound");
            currencies.Add("SEK - Swedish Krona");
            currencies.Add("SGD - Singapore Dollar");
            currencies.Add("SHP - Saint Helena Pound");
            currencies.Add("SLL - Sierra Leonean Leone");
            currencies.Add("SOS - Somali Shilling");
            currencies.Add("SRD - Surinamese Dollar");
            currencies.Add("STD - São Tomé and Príncipe Dobra");
            currencies.Add("SVC - Salvadoran Colón");
            currencies.Add("SYP - Syrian Pound");
            currencies.Add("SZL - Swazi Lilangeni");
            currencies.Add("WST - Samoan Tala");
            currencies.Add("XAG - Silver (troy ounce)");
            currencies.Add("XDR - Special Drawing Rights");
            currencies.Add("ZAR - South African Rand");
            currencies.Add("THB - Thai Baht");
            currencies.Add("TJS - Tajikistani Somoni");
            currencies.Add("TMT - Turkmenistani Manat");
            currencies.Add("TND - Tunisian Dinar");
            currencies.Add("TOP - Tongan Paʻanga");
            currencies.Add("TRY - Turkish Lira");
            currencies.Add("TTD - Trinidad and Tobago Dollar");
            currencies.Add("TZS - Tanzanian Shilling");
            currencies.Add("AED - United Arab Emirates Dirham");
            currencies.Add("UAH - Ukrainian Hryvnia");
            currencies.Add("UGX - Ugandan Shilling");
            currencies.Add("USD - United States Dollar");
            currencies.Add("UYU - Uruguayan Peso");
            currencies.Add("UZS - Uzbekistan Som");
            currencies.Add("VEF - Venezuelan Bolívar Fuerte");
            currencies.Add("VND - Vietnamese Dong");
            currencies.Add("VUV - Vanuatu Vatu");
            currencies.Add("YER - Yemeni Rial");
            currencies.Add("ZMK - Zambian Kwacha (pre-2013)");
            currencies.Add("ZMW - Zambian Kwacha");
            currencies.Add("ZWL - Zimbabwean Dolla");

            return currencies;

        }
    }
    
}
