using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MyAZHRM.Helpers
{
    public class CountryInfo
    {
        public List<string> getCountries()
        {
            List<string> countries = new List<string>();
            countries.Add("Afghanistan");
            countries.Add("Albania");
            countries.Add("Algeria");
            countries.Add("American Samoa");
            countries.Add("Andorra");
            countries.Add("Angola");
            countries.Add("Anguilla");
            countries.Add("Antarctica");
            countries.Add("Antigua and Barbuda");
            countries.Add("Argentina");
            countries.Add("Armenia");
            countries.Add("Aruba");
            countries.Add("Australia");
            countries.Add("Austria");
            countries.Add("Azerbaijan");
            countries.Add("Bahamas");
            countries.Add("Bahrain");
            countries.Add("Bangladesh");
            countries.Add("Barbados");
            countries.Add("Belarus");
            countries.Add("Belgium");
            countries.Add("Belize");
            countries.Add("Benin");
            countries.Add("Bermuda");
            countries.Add("Bhutan");
            countries.Add("Bolivia");
            countries.Add("Bosnia and Herzegovina");
            countries.Add("Botswana");
            countries.Add("Bouvet Island");
            countries.Add("Brazil");
            countries.Add("British Indian Ocean Territory");
            countries.Add("Brunei Darussalam");
            countries.Add("Bulgaria");
            countries.Add("Burkina Faso");
            countries.Add("Burundi");
            countries.Add("Cambodia");
            countries.Add("Cameroon");
            countries.Add("Canada");
            countries.Add("Cape Verde");
            countries.Add("Cayman Islands");
            countries.Add("Central African Republic");
            countries.Add("Chad");
            countries.Add("Chile");
            countries.Add("China");
            countries.Add("Christmas Island");
            countries.Add("Cocos Islands");
            countries.Add("Colombia");
            countries.Add("Comoros");
            countries.Add("Congo");
            countries.Add("Congo, the Democratic Republic of the");
            countries.Add("Cook Islands");
            countries.Add("Costa Rica");
            countries.Add("Cote D'Ivoire");
            countries.Add("Croatia");
            countries.Add("Cuba");
            countries.Add("Cyprus");
            countries.Add("Czech Republic");
            countries.Add("Denmark");
            countries.Add("Djibouti");
            countries.Add("Dominica");
            countries.Add("Dominican Republic");
            countries.Add("Ecuador");
            countries.Add("Egypt");
            countries.Add("El Salvador");
            countries.Add("England");
            countries.Add("Equatorial Guinea");
            countries.Add("Eritrea");
            countries.Add("Estonia");
            countries.Add("Eswatini");
            countries.Add("Ethiopia");
            countries.Add("Falkland Islands (Malvinas)");
            countries.Add("Faroe Islands");
            countries.Add("Fiji");
            countries.Add("Finland");
            countries.Add("France");
            countries.Add("French Guiana");
            countries.Add("French Polynesia");
            countries.Add("French Southern Territories");
            countries.Add("Gabon");
            countries.Add("Gambia");
            countries.Add("Georgia");
            countries.Add("Germany");
            countries.Add("Ghana");
            countries.Add("Gibraltar");
            countries.Add("Greece");
            countries.Add("Greenland");
            countries.Add("Grenada");
            countries.Add("Guadeloupe");
            countries.Add("Guam");
            countries.Add("Guatemala");
            countries.Add("Guinea");
            countries.Add("Guinea-Bissau");
            countries.Add("Guyana");
            countries.Add("Haiti");
            countries.Add("Heard Island and Mcdonald Islands");
            countries.Add("Holy See (Vatican City State)");
            countries.Add("Honduras");
            countries.Add("Hong Kong");
            countries.Add("Hungary");
            countries.Add("Iceland");
            countries.Add("India");
            countries.Add("Indonesia");
            countries.Add("Iran, Islamic Republic of");
            countries.Add("Iraq");
            countries.Add("Ireland");
            countries.Add("Israel");
            countries.Add("Italy");
            countries.Add("Jamaica");
            countries.Add("Japan");
            countries.Add("Jordan");
            countries.Add("Kazakhstan");
            countries.Add("Kenya");
            countries.Add("Kiribati");
            countries.Add("Korea, Democratic People's Republic of");
            countries.Add("Korea, Republic of");
            countries.Add("Kuwait");
            countries.Add("Kyrgyzstan");
            countries.Add("Lao People's Democratic Republic");
            countries.Add("Latvia");
            countries.Add("Lebanon");
            countries.Add("Lesotho");
            countries.Add("Liberia");
            countries.Add("Libyan Arab Jamahiriya");
            countries.Add("Liechtenstein");
            countries.Add("Lithuania");
            countries.Add("Luxembourg");
            countries.Add("Macao");
            countries.Add("Macedonia, the Former Yugoslav Republic of");
            countries.Add("Madagascar");
            countries.Add("Malawi");
            countries.Add("Malaysia");
            countries.Add("Maldives");
            countries.Add("Mali");
            countries.Add("Malta");
            countries.Add("Marshall Islands");
            countries.Add("Martinique");
            countries.Add("Mauritania");
            countries.Add("Mauritius");
            countries.Add("Mayotte");
            countries.Add("Mexico");
            countries.Add("Micronesia, Federated States of");
            countries.Add("Moldova, Republic of");
            countries.Add("Monaco");
            countries.Add("Mongolia");
            countries.Add("Montenegro");
            countries.Add("Montserrat");
            countries.Add("Morocco");
            countries.Add("Mozambique");
            countries.Add("Myanmar");
            countries.Add("Namibia");
            countries.Add("Nauru");
            countries.Add("Nepal");
            countries.Add("Netherlands");
            countries.Add("Netherlands Antilles");
            countries.Add("New Caledonia");
            countries.Add("New Zealand");
            countries.Add("Nicaragua");
            countries.Add("Niger");
            countries.Add("Nigeria");
            countries.Add("Niue");
            countries.Add("Norfolk Island");
            countries.Add("Northern Mariana Islands");
            countries.Add("Norway");
            countries.Add("Oman");
            countries.Add("Pakistan");
            countries.Add("Palau");
            countries.Add("Palestinian Territory, Occupied");
            countries.Add("Panama");
            countries.Add("Papua New Guinea");
            countries.Add("Paraguay");
            countries.Add("Peru");
            countries.Add("Philippines");
            countries.Add("Pitcairn");
            countries.Add("Poland");
            countries.Add("Portugal");
            countries.Add("Puerto Rico");
            countries.Add("Qatar");
            countries.Add("Reunion");
            countries.Add("Romania");
            countries.Add("Russian Federation");
            countries.Add("Rwanda");
            countries.Add("Saint Helena");
            countries.Add("Saint Kitts and Nevis");
            countries.Add("Saint Lucia");
            countries.Add("Saint Pierre and Miquelon");
            countries.Add("Saint Vincent and the Grenadines");
            countries.Add("Samoa");
            countries.Add("San Marino");
            countries.Add("Sao Tome and Principe");
            countries.Add("Saudi Arabia");
            countries.Add("Senegal");
            countries.Add("Serbia and Montenegro");
            countries.Add("Seychelles");
            countries.Add("Sierra Leone");
            countries.Add("Singapore");
            countries.Add("Slovakia");
            countries.Add("Slovenia");
            countries.Add("Solomon Islands");
            countries.Add("Somalia");
            countries.Add("South Africa");
            countries.Add("South Georgia and the South Sandwich Islands");
            countries.Add("South Sudan");
            countries.Add("Spain");
            countries.Add("Sri Lanka");
            countries.Add("Sudan");
            countries.Add("Suriname");
            countries.Add("Svalbard and Jan Mayen");
            countries.Add("Swaziland");
            countries.Add("Sweden");
            countries.Add("Switzerland");
            countries.Add("Syrian Arab Republic");
            countries.Add("Taiwan, Province of China");
            countries.Add("Tajikistan");
            countries.Add("Tanzania, United Republic of");
            countries.Add("Thailand");
            countries.Add("Timor-Leste");
            countries.Add("Togo");
            countries.Add("Tokelau");
            countries.Add("Tonga");
            countries.Add("Trinidad and Tobago");
            countries.Add("Tunisia");
            countries.Add("Turkey");
            countries.Add("Turkmenistan");
            countries.Add("Turks and Caicos Islands");
            countries.Add("Tuvalu");
            countries.Add("Uganda");
            countries.Add("Ukraine");
            countries.Add("United Arab Emirates");
            countries.Add("United Kingdom");
            countries.Add("United States");
            countries.Add("United States Minor Outlying Islands");
            countries.Add("Uruguay");
            countries.Add("Uzbekistan");
            countries.Add("Vanuatu");
            countries.Add("Venezuela");
            countries.Add("Viet Nam");
            countries.Add("Virgin Islands, British");
            countries.Add("Virgin Islands, US");
            countries.Add("Wales");
            countries.Add("Wallis and Futuna");
            countries.Add("Western Sahara");
            countries.Add("Yemen");
            countries.Add("Zambia");
            countries.Add("Zimbabwe");
            return countries;

        }
    }
    
}
